apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "500"
      port: 500
      protocol: UDP
      targetPort: 500
    - name: "4500"
      port: 4500
      protocol: UDP
      targetPort: 4500
    - name: "1701"
      port: 1701
      targetPort: 1701
    - name: "1194"
      port: 1194
      protocol: UDP
      targetPort: 1194
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
